FROM golang:1.13.6
WORKDIR /
RUN go version
RUN mkdir -p app/WikiGoApp/client/build
WORKDIR /home/app/WikiGoApp/client/build
ADD ./client/build .

WORKDIR /home/app/WikiGoApp
ADD ./main.go .
RUN go mod init github.com/sauravsehgal24/WikiGoApp
RUN go mod download
RUN go get
RUN go build main.go
EXPOSE 8080
ENTRYPOINT ["./main"]
RUN ls 
