

FROM golang:alpine3.9
FROM node:alpine
RUN ls
# WORKDIR $GOPATH/src/github.com/sauravsehgal24/WikiGoApp
# RUN export PATH=$PATH:/usr/local/go/bin

# WORKDIR /go/src/WikiGoApp/client
# # RUN mkdir client
# # WORKDIR /go/src/WikiGoApp/client
# ADD ./client/ .
# RUN npm install
# RUN npm run build
# WORKDIR /go/src/WikiGoApp/

# ADD . .
# RUN go get
# RUN go build
# RUN ls 
