FROM ubuntu:14.04

MAINTAINER saurav

RUN apt-get update
RUN apt-get install -y nginx
RUN apt-get install -y golang-go
RUN apt-get install -y npm

WORKDIR /home/app
ADD . .

WORKDIR /home/app
RUN go build
EXPOSE 8080
ENTRYPOINT ["./app"]

